spring:
  application:
    name: spring-boot-study

  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: mkjy9821!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true